from __future__ import annotations

import hashlib
import math
import random
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from pokemon_red_ai.self_taught import (
    SELF_GENERATED_COMPOSITION_PROTOCOL,
    SELF_GENERATED_REPLAY_SHARD_PROTOCOL,
)


@dataclass(frozen=True, slots=True)
class SequenceTrainingConfig:
    """Configuration for sequence-aware behavior cloning of verified skills."""

    burn_in: int = 64
    train_length: int = 128
    stride: int = 64
    learning_rate: float = 3e-4
    max_grad_norm: float = 0.5
    diagnostic_chunk_length: int = 512
    max_examples_per_dataset: int = 512

    def __post_init__(self) -> None:
        if self.burn_in < 0:
            raise ValueError("Sequence burn-in cannot be negative")
        if self.train_length < 1:
            raise ValueError("Sequence train length must be positive")
        if not 1 <= self.stride <= self.train_length:
            raise ValueError("Sequence stride must be between one and train length")
        if not math.isfinite(self.learning_rate) or self.learning_rate <= 0:
            raise ValueError("Student learning rate must be positive and finite")
        if not math.isfinite(self.max_grad_norm) or self.max_grad_norm <= 0:
            raise ValueError("Student gradient clipping must be positive and finite")
        if self.diagnostic_chunk_length < 1:
            raise ValueError("Diagnostic chunk length must be positive")
        if self.max_examples_per_dataset < 1:
            raise ValueError("Student replay example cap must be positive")


@dataclass(frozen=True, slots=True)
class SelfGeneratedSkillDataset:
    """One replay-verified trajectory generated by the agent itself."""

    skill_id: str
    path: Path
    pixels: np.ndarray
    action_history: np.ndarray
    target_pixels: np.ndarray
    actions: np.ndarray
    weights: np.ndarray
    episode_starts: np.ndarray
    goal_indices: np.ndarray
    excerpt_offsets: tuple[int, ...]
    source_action_count: int
    source_action_offset: int
    target_is_temporal: bool = False
    target_is_segmented: bool = False
    dataset_kind: str = "skill"
    source_skill_ids: tuple[str, ...] = ()
    goal_switch_offsets: tuple[int, ...] = ()
    successful_replays: int = 0
    replay_shard_protocol: str | None = None
    source_dataset_sha256: str | None = None
    replay_shard_index: int = 0
    replay_shard_count: int = 0
    train_offset: int = 0
    source_train_start: int = 0
    source_train_stop: int = 0

    @classmethod
    def load(
        cls,
        path: Path,
        *,
        skill_id: str | None = None,
        max_examples: int | None = None,
        sample_seed: int = 0,
    ) -> SelfGeneratedSkillDataset:
        resolved = Path(path).expanduser().resolve()
        identifier = skill_id or resolved.stem
        if not identifier:
            raise ValueError("Self-generated dataset requires a skill identifier")
        with np.load(resolved, allow_pickle=False) as archive:
            required = {"pixels", "action_history", "target_pixels", "actions"}
            missing = sorted(required.difference(archive.files))
            if missing:
                raise ValueError(f"Self-generated dataset is missing: {', '.join(missing)}")
            pixels = np.asarray(archive["pixels"], dtype=np.uint8)
            histories = np.asarray(archive["action_history"], dtype=np.float32)
            target = np.asarray(archive["target_pixels"], dtype=np.uint8)
            actions = np.asarray(archive["actions"], dtype=np.int64)
            weights = (
                np.asarray(archive["weights"], dtype=np.float32)
                if "weights" in archive.files
                else np.ones(len(actions), dtype=np.float32)
            )
            dataset_kind = (
                str(np.asarray(archive["dataset_kind"]).item())
                if "dataset_kind" in archive.files
                else "skill"
            )
            source_skill_ids = (
                tuple(str(value) for value in np.asarray(archive["source_skill_ids"]).tolist())
                if "source_skill_ids" in archive.files
                else ()
            )
            goal_switch_offsets = (
                tuple(int(value) for value in np.asarray(archive["goal_switch_offsets"]).tolist())
                if "goal_switch_offsets" in archive.files
                else ()
            )
            replay_protocol = (
                str(np.asarray(archive["replay_protocol"]).item())
                if "replay_protocol" in archive.files
                else None
            )
            successful_replays = (
                int(np.asarray(archive["successful_replays"]).item())
                if "successful_replays" in archive.files
                else 0
            )
            episode_starts = (
                np.asarray(archive["episode_starts"], dtype=np.bool_)
                if "episode_starts" in archive.files
                else None
            )
            goal_indices = (
                np.asarray(archive["goal_indices"], dtype=np.int64)
                if "goal_indices" in archive.files
                else None
            )
            excerpt_offsets = (
                tuple(int(value) for value in np.asarray(archive["excerpt_offsets"]).tolist())
                if "excerpt_offsets" in archive.files
                else ()
            )
            replay_shard_protocol = (
                str(np.asarray(archive["replay_shard_protocol"]).item())
                if "replay_shard_protocol" in archive.files
                else None
            )
            source_dataset_sha256 = (
                str(np.asarray(archive["source_dataset_sha256"]).item())
                if "source_dataset_sha256" in archive.files
                else None
            )
            source_skill_id = (
                str(np.asarray(archive["source_skill_id"]).item())
                if "source_skill_id" in archive.files
                else None
            )
            embedded_source_action_count = (
                int(np.asarray(archive["source_action_count"]).item())
                if "source_action_count" in archive.files
                else None
            )
            embedded_source_action_offset = (
                int(np.asarray(archive["source_action_offset"]).item())
                if "source_action_offset" in archive.files
                else None
            )
            embedded_source_context_start = (
                int(np.asarray(archive["source_context_start"]).item())
                if "source_context_start" in archive.files
                else None
            )
            embedded_source_train_start = (
                int(np.asarray(archive["source_train_start"]).item())
                if "source_train_start" in archive.files
                else None
            )
            embedded_source_train_stop = (
                int(np.asarray(archive["source_train_stop"]).item())
                if "source_train_stop" in archive.files
                else None
            )
            replay_shard_index = (
                int(np.asarray(archive["replay_shard_index"]).item())
                if "replay_shard_index" in archive.files
                else 0
            )
            replay_shard_count = (
                int(np.asarray(archive["replay_shard_count"]).item())
                if "replay_shard_count" in archive.files
                else 0
            )
            replay_train_offset = (
                int(np.asarray(archive["replay_train_offset"]).item())
                if "replay_train_offset" in archive.files
                else 0
            )

        source_action_count = len(actions)
        source_action_offset = 0
        if replay_shard_protocol is not None:
            if replay_shard_protocol != SELF_GENERATED_REPLAY_SHARD_PROTOCOL:
                raise ValueError("Unsupported self-generated replay shard protocol")
            if max_examples is not None:
                raise ValueError("Admission-time replay shards cannot be sampled again")
            if (
                source_skill_id != identifier
                or source_dataset_sha256 is None
                or len(source_dataset_sha256) != 64
                or any(
                    character not in "0123456789abcdef"
                    for character in source_dataset_sha256
                )
                or embedded_source_action_count is None
                or embedded_source_action_offset is None
                or embedded_source_context_start is None
                or embedded_source_train_start is None
                or embedded_source_train_stop is None
                or embedded_source_action_count < len(actions)
                or not 0 <= embedded_source_action_offset
                <= embedded_source_action_count - len(actions)
                or replay_shard_count < 1
                or not 0 <= replay_shard_index < replay_shard_count
                or not 0 <= replay_train_offset < len(actions)
                or embedded_source_context_start != embedded_source_action_offset
                or embedded_source_train_start
                != embedded_source_context_start + replay_train_offset
                or embedded_source_train_stop
                != embedded_source_context_start + len(actions)
                or embedded_source_train_stop > embedded_source_action_count
            ):
                raise ValueError("Self-generated replay shard metadata is invalid")
            source_action_count = embedded_source_action_count
            source_action_offset = embedded_source_action_offset
        elif replay_train_offset != 0:
            raise ValueError("Only an admission-time replay shard may declare loss-free context")
        if max_examples is not None and max_examples < 1:
            raise ValueError("Student replay example cap must be positive")
        if dataset_kind == "skill" and max_examples is not None and len(actions) > max_examples:
            choices = len(actions) - max_examples + 1
            identity = hashlib.sha256(
                f"{sample_seed}:{identifier}:{len(actions)}".encode()
            ).digest()
            source_action_offset = int.from_bytes(identity[:8], "big") % choices
            stop = source_action_offset + max_examples
            pixels = pixels[source_action_offset:stop].copy()
            histories = histories[source_action_offset:stop].copy()
            actions = actions[source_action_offset:stop].copy()
            weights = weights[source_action_offset:stop].copy()
            episode_starts = np.asarray(
                [True, *([False] * (len(actions) - 1))],
                dtype=np.bool_,
            )
        if actions.ndim != 1 or len(actions) < 1:
            raise ValueError("Self-generated actions must be a non-empty vector")
        if np.any(actions < 0):
            raise ValueError("Self-generated action indices cannot be negative")
        if (
            weights.shape != actions.shape
            or not np.all(np.isfinite(weights))
            or np.any(weights <= 0)
        ):
            raise ValueError("Self-generated action weights must be positive and finite")
        if pixels.ndim < 2 or pixels.shape[0] != len(actions):
            raise ValueError("Pixel observations must have one leading item per action")
        if histories.ndim < 2 or histories.shape[0] != len(actions):
            raise ValueError("Action histories must have one leading item per action")

        if episode_starts is None:
            episode_starts = np.asarray(
                [True, *([False] * (len(actions) - 1))],
                dtype=np.bool_,
            )
        if goal_indices is None:
            goal_indices = np.zeros(len(actions), dtype=np.int64)
        if not excerpt_offsets:
            excerpt_offsets = (0, len(actions))

        target_is_temporal = target.ndim == pixels.ndim and target.shape[0] == len(actions)
        target_is_segmented = (
            dataset_kind == "composition"
            and target.ndim == pixels.ndim
            and target.shape[0] == len(source_skill_ids)
        )
        if not target_is_temporal and not target_is_segmented and target.ndim != pixels.ndim - 1:
            raise ValueError("Target pixels must be one static frame or one frame per action")
        if dataset_kind not in {"skill", "composition"}:
            raise ValueError("Self-generated dataset kind is unsupported")
        if episode_starts.shape != actions.shape or not bool(episode_starts[0]):
            raise ValueError("Self-generated episode boundaries must include the first action")
        if goal_indices.shape != actions.shape:
            raise ValueError("Self-generated goal indices must cover every retained action")
        if (
            excerpt_offsets[0] != 0
            or excerpt_offsets[-1] != len(actions)
            or any(
                left >= right
                for left, right in zip(excerpt_offsets, excerpt_offsets[1:], strict=False)
            )
        ):
            raise ValueError("Self-generated excerpt boundaries are invalid")
        expected_starts = np.zeros(len(actions), dtype=np.bool_)
        expected_starts[np.asarray(excerpt_offsets[:-1], dtype=np.int64)] = True
        if not np.array_equal(episode_starts, expected_starts):
            raise ValueError("Self-generated episode starts disagree with excerpt boundaries")
        if dataset_kind == "composition":
            if replay_protocol != SELF_GENERATED_COMPOSITION_PROTOCOL:
                raise ValueError("Composition dataset lacks self-generated replay provenance")
            if successful_replays < 1:
                raise ValueError("Composition dataset has no successful continuous replay")
            if len(source_skill_ids) < 2 or len(source_skill_ids) != len(set(source_skill_ids)):
                raise ValueError("Composition dataset needs two or more unique source skills")
            if (
                len(goal_switch_offsets) != len(source_skill_ids) - 1
                or any(not 0 < boundary < len(actions) for boundary in goal_switch_offsets)
                or any(
                    left >= right
                    for left, right in zip(
                        goal_switch_offsets,
                        goal_switch_offsets[1:],
                        strict=False,
                    )
                )
            ):
                raise ValueError("Composition dataset goal-switch boundaries are invalid")
            if not target_is_segmented:
                raise ValueError("Composition goals must use compact per-skill clips")
            if np.any(goal_indices < 0) or np.any(goal_indices >= len(source_skill_ids)):
                raise ValueError("Composition goal indices reference an unknown skill")
            if any(
                goal_indices[boundary - 1] == goal_indices[boundary]
                for boundary in goal_switch_offsets
            ):
                raise ValueError("Composition goal switches must change the active clip")
            observed_switches = set(
                int(value)
                for value in np.flatnonzero(goal_indices[1:] != goal_indices[:-1]) + 1
                if int(value) not in set(excerpt_offsets[:-1])
            )
            if observed_switches != set(goal_switch_offsets):
                raise ValueError("Composition contains an undeclared in-excerpt goal switch")
        elif source_skill_ids or goal_switch_offsets or replay_protocol is not None:
            raise ValueError("Individual skill dataset contains composition metadata")
        return cls(
            skill_id=str(identifier),
            path=resolved,
            pixels=pixels,
            action_history=histories,
            target_pixels=target,
            actions=actions,
            weights=weights,
            episode_starts=episode_starts,
            goal_indices=goal_indices,
            excerpt_offsets=excerpt_offsets,
            source_action_count=source_action_count,
            source_action_offset=source_action_offset,
            target_is_temporal=target_is_temporal,
            target_is_segmented=target_is_segmented,
            dataset_kind=dataset_kind,
            source_skill_ids=source_skill_ids,
            goal_switch_offsets=goal_switch_offsets,
            successful_replays=successful_replays,
            replay_shard_protocol=replay_shard_protocol,
            source_dataset_sha256=source_dataset_sha256,
            replay_shard_index=replay_shard_index,
            replay_shard_count=replay_shard_count,
            train_offset=replay_train_offset,
            source_train_start=(
                source_action_offset + replay_train_offset
                if embedded_source_train_start is None
                else embedded_source_train_start
            ),
            source_train_stop=(
                source_action_offset + len(actions)
                if embedded_source_train_stop is None
                else embedded_source_train_stop
            ),
        )

    def __len__(self) -> int:
        return len(self.actions)

    def observations(self, begin: int, end: int) -> dict[str, np.ndarray]:
        if not 0 <= begin <= end <= len(self):
            raise ValueError("Observation slice lies outside its skill trajectory")
        count = end - begin
        if self.target_is_segmented:
            targets = self.target_pixels[self.goal_indices[begin:end]]
        elif self.target_is_temporal:
            targets = self.target_pixels[begin:end]
        else:
            targets = np.repeat(self.target_pixels[None, ...], count, axis=0)
        return {
            "pixels": self.pixels[begin:end],
            "action_history": self.action_history[begin:end],
            "target_pixels": targets,
        }

    @property
    def episode_ranges(self) -> tuple[tuple[int, int], ...]:
        return tuple(zip(self.excerpt_offsets, self.excerpt_offsets[1:], strict=False))

    def is_episode_start(self, index: int) -> bool:
        return bool(self.episode_starts[index])

    @property
    def retained_bytes(self) -> int:
        return sum(
            array.nbytes
            for array in (
                self.pixels,
                self.action_history,
                self.target_pixels,
                self.actions,
                self.weights,
                self.episode_starts,
                self.goal_indices,
            )
        )

    @property
    def trainable_examples(self) -> int:
        return len(self.actions) - self.train_offset

    @property
    def trainable_actions(self) -> np.ndarray:
        return self.actions[self.train_offset :]


@dataclass(frozen=True, slots=True)
class RecurrentSequence:
    """A train region plus its immediately preceding, loss-free context."""

    dataset: SelfGeneratedSkillDataset
    burn_start: int
    train_start: int
    train_stop: int

    @property
    def skill_id(self) -> str:
        return self.dataset.skill_id

    @property
    def burn_length(self) -> int:
        return self.train_start - self.burn_start

    @property
    def train_examples(self) -> int:
        return self.train_stop - self.train_start

    @property
    def crossed_goal_switches(self) -> tuple[int, ...]:
        """Declared goal switches represented on both sides of this train region."""

        return tuple(
            boundary
            for boundary in self.dataset.goal_switch_offsets
            if self.train_start < boundary < self.train_stop
        )


def make_recurrent_sequences(
    dataset: SelfGeneratedSkillDataset,
    *,
    burn_in: int,
    train_length: int,
    stride: int,
) -> tuple[RecurrentSequence, ...]:
    """Cover a trajectory with overlapping train regions and bounded burn-in prefixes."""

    if burn_in < 0 or train_length < 1 or not 1 <= stride <= train_length:
        raise ValueError("Invalid recurrent sequence dimensions")
    sequences: list[RecurrentSequence] = []
    for episode_start, episode_stop in dataset.episode_ranges:
        first_train_start = max(episode_start, dataset.train_offset)
        for train_start in range(first_train_start, episode_stop, stride):
            sequences.append(
                RecurrentSequence(
                    dataset=dataset,
                    burn_start=max(episode_start, train_start - burn_in),
                    train_start=train_start,
                    train_stop=min(episode_stop, train_start + train_length),
                )
            )
    if dataset.dataset_kind == "composition":
        # Add explicit windows around every declared goal switch. Their burn-in is
        # drawn from the preceding skill, so the recurrent state and action-history
        # cross the boundary instead of treating each option as a new episode.
        for boundary in dataset.goal_switch_offsets:
            excerpt_start, excerpt_stop = next(
                (start, stop) for start, stop in dataset.episode_ranges if start < boundary < stop
            )
            train_start = max(excerpt_start, boundary - max(1, train_length // 2))
            train_stop = min(excerpt_stop, train_start + train_length)
            if train_stop - train_start < train_length:
                train_start = max(excerpt_start, train_stop - train_length)
            candidate = RecurrentSequence(
                dataset=dataset,
                burn_start=max(excerpt_start, train_start - burn_in),
                train_start=train_start,
                train_stop=train_stop,
            )
            if all(
                (existing.burn_start, existing.train_start, existing.train_stop)
                != (candidate.burn_start, candidate.train_start, candidate.train_stop)
                for existing in sequences
            ):
                sequences.append(candidate)
        sequences.sort(key=lambda value: (value.train_start, value.train_stop, value.burn_start))
    return tuple(sequences)


class BalancedSkillReplay:
    """Balanced local replay plus non-vanishing composition transition rehearsal."""

    def __init__(
        self,
        datasets: Iterable[SelfGeneratedSkillDataset],
        config: SequenceTrainingConfig,
        *,
        seed: int = 0,
        composition_boundary_cursor: int = 0,
    ) -> None:
        materialized = list(datasets)
        identifiers = [dataset.skill_id for dataset in materialized]
        if not materialized:
            raise ValueError("Balanced replay requires at least one skill")
        if len(identifiers) != len(set(identifiers)):
            raise ValueError("Balanced replay skill identifiers must be unique")
        self.config = config
        self._random = random.Random(seed)
        if composition_boundary_cursor < 0:
            raise ValueError("Composition boundary cursor cannot be negative")
        self._base_boundary_cursor = composition_boundary_cursor
        self._boundary_draws = 0
        self._sequences: dict[str, tuple[RecurrentSequence, ...]] = {}
        self._boundary_sequences: dict[str, dict[int, tuple[RecurrentSequence, ...]]] = {}
        self._composition_draws: dict[str, int] = {}
        self._sampling_weights: dict[str, int] = {}
        self._cycle: list[str] = []
        for dataset in materialized:
            self.register(dataset)

    @property
    def skill_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self._sequences))

    @property
    def sampling_cycle_size(self) -> int:
        return sum(self._sampling_weights.values())

    @property
    def next_composition_boundary_cursor(self) -> int:
        return self._base_boundary_cursor + self._boundary_draws

    def _refill_cycle(self) -> None:
        self._cycle = [
            skill_id for skill_id in self.skill_ids for _ in range(self._sampling_weights[skill_id])
        ]
        self._random.shuffle(self._cycle)

    def sample_one(self) -> RecurrentSequence:
        if not self._cycle:
            self._refill_cycle()
        skill_id = self._cycle.pop()
        boundary_sequences = self._boundary_sequences.get(skill_id, {})
        draw = self._composition_draws.get(skill_id, 0)
        self._composition_draws[skill_id] = draw + 1
        if boundary_sequences and draw % 2 == 0:
            boundaries = tuple(sorted(boundary_sequences))
            boundary = boundaries[
                (self._base_boundary_cursor + self._boundary_draws) % len(boundaries)
            ]
            self._boundary_draws += 1
            return self._random.choice(boundary_sequences[boundary])
        return self._random.choice(self._sequences[skill_id])

    def sample(self, count: int) -> tuple[RecurrentSequence, ...]:
        if count < 1:
            raise ValueError("Replay sample count must be positive")
        return tuple(self.sample_one() for _ in range(count))

    def register(
        self,
        dataset: SelfGeneratedSkillDataset,
        *,
        replace: bool = False,
    ) -> None:
        """Add a newly discovered skill without rebuilding the continuous replay object."""

        if dataset.skill_id in self._sequences and not replace:
            raise ValueError("Balanced replay already contains this skill")
        sequences = make_recurrent_sequences(
            dataset,
            burn_in=self.config.burn_in,
            train_length=self.config.train_length,
            stride=self.config.stride,
        )
        self._sequences[dataset.skill_id] = sequences
        self._boundary_sequences[dataset.skill_id] = {
            boundary: tuple(
                sequence for sequence in sequences if boundary in sequence.crossed_goal_switches
            )
            for boundary in dataset.goal_switch_offsets
        }
        if any(not windows for windows in self._boundary_sequences[dataset.skill_id].values()):
            raise ValueError("Composition replay has an uncovered goal-switch boundary")
        self._composition_draws[dataset.skill_id] = 0
        self._sampling_weights[dataset.skill_id] = (
            len(dataset.source_skill_ids) if dataset.dataset_kind == "composition" else 1
        )
        # Discard any stale cycle so the next draw includes the new skill.
        self._cycle.clear()

    def window_counts(self) -> dict[str, int]:
        return {skill_id: len(windows) for skill_id, windows in self._sequences.items()}


@dataclass(frozen=True, slots=True)
class SkillDiagnostics:
    examples: int
    updates: int
    action_nll: float
    action_accuracy: float
    policy_entropy: float
    demonstration_entropy: float

    def public_dict(self) -> dict[str, int | float]:
        return {
            "examples": self.examples,
            "updates": self.updates,
            "action_nll": self.action_nll,
            "action_accuracy": self.action_accuracy,
            "policy_entropy": self.policy_entropy,
            "demonstration_entropy": self.demonstration_entropy,
        }


@dataclass(frozen=True, slots=True)
class StudentTrainingReport:
    updates: int
    train_examples: int
    burn_in_examples: int
    mean_action_nll: float
    mean_action_accuracy: float
    mean_policy_entropy: float
    per_skill: dict[str, SkillDiagnostics]

    def public_dict(self) -> dict[str, Any]:
        return {
            "updates": self.updates,
            "train_examples": self.train_examples,
            "burn_in_examples": self.burn_in_examples,
            "mean_action_nll": self.mean_action_nll,
            "mean_action_accuracy": self.mean_action_accuracy,
            "mean_policy_entropy": self.mean_policy_entropy,
            "per_skill": {
                skill_id: diagnostics.public_dict()
                for skill_id, diagnostics in sorted(self.per_skill.items())
            },
        }


@dataclass(slots=True)
class _MetricAccumulator:
    examples: int = 0
    updates: int = 0
    nll_total: float = 0.0
    correct: int = 0
    entropy_total: float = 0.0

    def add(self, *, count: int, nll: float, correct: int, entropy: float) -> None:
        self.examples += count
        self.updates += 1
        self.nll_total += nll * count
        self.correct += correct
        self.entropy_total += entropy * count


def _demonstration_entropy(actions: np.ndarray) -> float:
    _values, counts = np.unique(actions, return_counts=True)
    probabilities = counts.astype(np.float64) / counts.sum()
    return float(-(probabilities * np.log(probabilities)).sum())


class SequenceAwareStudentTrainer:
    """Separate-optimizer recurrent behavior cloning for an SB3 RecurrentPPO policy."""

    def __init__(
        self,
        model: Any,
        config: SequenceTrainingConfig,
        *,
        optimizer: Any | None = None,
    ) -> None:
        import torch

        self.model = model
        self.policy = model.policy
        self.config = config
        required = ("lstm_actor", "mlp_extractor", "action_net", "extract_features")
        if any(not hasattr(self.policy, name) for name in required):
            raise TypeError("Student trainer requires an sb3-contrib recurrent actor policy")
        self.actor_parameters = self._collect_actor_parameters()
        self.optimizer = optimizer or torch.optim.Adam(
            self.actor_parameters,
            lr=config.learning_rate,
        )

    def optimizer_state_dict(self) -> dict[str, Any]:
        """Return the separate Student optimizer state for crash-safe checkpoints."""

        return self.optimizer.state_dict()

    def load_optimizer_state_dict(self, state: Mapping[str, Any]) -> None:
        self.optimizer.load_state_dict(dict(state))

    def _collect_actor_parameters(self) -> list[Any]:
        modules = []
        extractor_name = (
            "features_extractor"
            if bool(getattr(self.policy, "share_features_extractor", True))
            else "pi_features_extractor"
        )
        for name in (extractor_name, "lstm_actor", "action_net"):
            module = getattr(self.policy, name, None)
            if module is not None:
                modules.append(module)
        policy_net = getattr(self.policy.mlp_extractor, "policy_net", None)
        if policy_net is not None:
            modules.append(policy_net)
        parameters: list[Any] = []
        seen: set[int] = set()
        for module in modules:
            for parameter in module.parameters():
                if parameter.requires_grad and id(parameter) not in seen:
                    seen.add(id(parameter))
                    parameters.append(parameter)
        if not parameters:
            raise TypeError("Recurrent actor exposes no trainable parameters")
        return parameters

    def _tensor_observations(self, observations: Mapping[str, np.ndarray]) -> dict[str, Any]:
        import torch

        return {
            name: torch.as_tensor(value, device=self.policy.device)
            for name, value in observations.items()
        }

    def _zero_actor_state(self) -> tuple[Any, Any]:
        import torch

        recurrent = self.policy.lstm_actor
        shape = (recurrent.num_layers, 1, recurrent.hidden_size)
        hidden = torch.zeros(shape, device=self.policy.device)
        return hidden, hidden.clone()

    def _validate_actions(self, dataset: SelfGeneratedSkillDataset) -> None:
        action_count = getattr(getattr(self.model, "action_space", None), "n", None)
        if action_count is not None and np.any(dataset.actions >= int(action_count)):
            raise ValueError("Self-generated dataset contains an unavailable action")

    def _actor_distribution(
        self,
        observations: Mapping[str, np.ndarray],
        state: tuple[Any, Any],
        *,
        starts_episode: bool,
    ) -> tuple[Any, tuple[Any, Any]]:
        import torch

        tensors = self._tensor_observations(observations)
        features = self.policy.extract_features(tensors)
        actor_features = features[0] if isinstance(features, tuple) else features
        count = int(actor_features.shape[0])
        episode_starts = torch.zeros(count, device=self.policy.device)
        if starts_episode and count:
            episode_starts[0] = 1.0
        latent, next_state = self.policy._process_sequence(
            actor_features,
            state,
            episode_starts,
            self.policy.lstm_actor,
        )
        latent = self.policy.mlp_extractor.forward_actor(latent)
        return self.policy._get_action_dist_from_latent(latent), next_state

    def train_sequence(self, sequence: RecurrentSequence) -> StudentTrainingReport:
        import torch

        dataset = sequence.dataset
        self._validate_actions(dataset)
        previous_mode = bool(self.policy.training)
        self.policy.set_training_mode(True)
        state = self._zero_actor_state()
        if sequence.burn_length:
            with torch.no_grad():
                _distribution, state = self._actor_distribution(
                    dataset.observations(sequence.burn_start, sequence.train_start),
                    state,
                    starts_episode=dataset.is_episode_start(sequence.burn_start),
                )
            state = tuple(value.detach() for value in state)

        distribution, _next_state = self._actor_distribution(
            dataset.observations(sequence.train_start, sequence.train_stop),
            state,
            starts_episode=dataset.is_episode_start(sequence.train_start),
        )
        actions = torch.as_tensor(
            dataset.actions[sequence.train_start : sequence.train_stop],
            dtype=torch.long,
            device=self.policy.device,
        )
        log_probability = distribution.log_prob(actions)
        weights = torch.as_tensor(
            dataset.weights[sequence.train_start : sequence.train_stop],
            dtype=torch.float32,
            device=self.policy.device,
        )
        entropy_tensor = distribution.entropy()
        if entropy_tensor is None:
            raise TypeError("Student trainer requires a policy distribution with entropy")
        loss = -(log_probability * weights).sum() / weights.sum()
        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.actor_parameters, self.config.max_grad_norm)
        self.optimizer.step()

        predictions = distribution.mode()
        count = sequence.train_examples
        correct = int((predictions == actions).sum().detach().item())
        nll = float((-log_probability).mean().detach().item())
        entropy = float(entropy_tensor.mean().detach().item())
        self.policy.set_training_mode(previous_mode)
        diagnostics = SkillDiagnostics(
            examples=count,
            updates=1,
            action_nll=nll,
            action_accuracy=correct / count,
            policy_entropy=entropy,
            demonstration_entropy=_demonstration_entropy(dataset.trainable_actions),
        )
        return StudentTrainingReport(
            updates=1,
            train_examples=count,
            burn_in_examples=sequence.burn_length,
            mean_action_nll=nll,
            mean_action_accuracy=correct / count,
            mean_policy_entropy=entropy,
            per_skill={dataset.skill_id: diagnostics},
        )

    def train(self, replay: BalancedSkillReplay, *, updates: int) -> StudentTrainingReport:
        if updates < 1:
            raise ValueError("Student training requires at least one update")
        accumulators: dict[str, _MetricAccumulator] = {}
        demonstrations: dict[str, np.ndarray] = {}
        burn_in_examples = 0
        for sequence in replay.sample(updates):
            report = self.train_sequence(sequence)
            skill_id = sequence.skill_id
            metric = report.per_skill[skill_id]
            accumulator = accumulators.setdefault(skill_id, _MetricAccumulator())
            accumulator.add(
                count=metric.examples,
                nll=metric.action_nll,
                correct=round(metric.action_accuracy * metric.examples),
                entropy=metric.policy_entropy,
            )
            demonstrations[skill_id] = sequence.dataset.actions
            burn_in_examples += report.burn_in_examples
        per_skill = {
            skill_id: SkillDiagnostics(
                examples=value.examples,
                updates=value.updates,
                action_nll=value.nll_total / value.examples,
                action_accuracy=value.correct / value.examples,
                policy_entropy=value.entropy_total / value.examples,
                demonstration_entropy=_demonstration_entropy(demonstrations[skill_id]),
            )
            for skill_id, value in accumulators.items()
        }
        total_examples = sum(value.examples for value in accumulators.values())
        return StudentTrainingReport(
            updates=updates,
            train_examples=total_examples,
            burn_in_examples=burn_in_examples,
            mean_action_nll=(
                sum(value.nll_total for value in accumulators.values()) / total_examples
            ),
            mean_action_accuracy=(
                sum(value.correct for value in accumulators.values()) / total_examples
            ),
            mean_policy_entropy=(
                sum(value.entropy_total for value in accumulators.values()) / total_examples
            ),
            per_skill=per_skill,
        )

    def diagnose(
        self,
        datasets: Iterable[SelfGeneratedSkillDataset],
    ) -> dict[str, SkillDiagnostics]:
        """Measure every action exactly once while carrying recurrent state forward."""

        import torch

        results: dict[str, SkillDiagnostics] = {}
        previous_mode = bool(self.policy.training)
        self.policy.set_training_mode(False)
        with torch.no_grad():
            for dataset in datasets:
                self._validate_actions(dataset)
                accumulator = _MetricAccumulator()
                for episode_start, episode_stop in dataset.episode_ranges:
                    state = self._zero_actor_state()
                    first_train_start = max(episode_start, dataset.train_offset)
                    if first_train_start > episode_start:
                        _distribution, state = self._actor_distribution(
                            dataset.observations(episode_start, first_train_start),
                            state,
                            starts_episode=True,
                        )
                    for begin in range(
                        first_train_start,
                        episode_stop,
                        self.config.diagnostic_chunk_length,
                    ):
                        end = min(
                            episode_stop,
                            begin + self.config.diagnostic_chunk_length,
                        )
                        distribution, state = self._actor_distribution(
                            dataset.observations(begin, end),
                            state,
                            starts_episode=begin == episode_start,
                        )
                        actions = torch.as_tensor(
                            dataset.actions[begin:end],
                            dtype=torch.long,
                            device=self.policy.device,
                        )
                        negative_log_probability = -distribution.log_prob(actions)
                        entropy_tensor = distribution.entropy()
                        if entropy_tensor is None:
                            raise TypeError(
                                "Student trainer requires a policy distribution with entropy"
                            )
                        accumulator.add(
                            count=end - begin,
                            nll=float(negative_log_probability.mean().item()),
                            correct=int((distribution.mode() == actions).sum().item()),
                            entropy=float(entropy_tensor.mean().item()),
                        )
                results[dataset.skill_id] = SkillDiagnostics(
                    examples=accumulator.examples,
                    updates=0,
                    action_nll=accumulator.nll_total / accumulator.examples,
                    action_accuracy=accumulator.correct / accumulator.examples,
                    policy_entropy=accumulator.entropy_total / accumulator.examples,
                    demonstration_entropy=_demonstration_entropy(dataset.trainable_actions),
                )
        self.policy.set_training_mode(previous_mode)
        return results


def load_self_generated_datasets(
    paths: Mapping[str, Path] | Sequence[Path],
    *,
    max_examples_per_skill: int | None = None,
    sample_seed: int = 0,
) -> tuple[SelfGeneratedSkillDataset, ...]:
    """Load skill files with explicit IDs, or derive IDs from unique file stems."""

    if isinstance(paths, Mapping):
        datasets = [
            SelfGeneratedSkillDataset.load(
                path,
                skill_id=skill_id,
                max_examples=max_examples_per_skill,
                sample_seed=sample_seed,
            )
            for skill_id, path in paths.items()
        ]
    else:
        datasets = [
            SelfGeneratedSkillDataset.load(
                path,
                max_examples=max_examples_per_skill,
                sample_seed=sample_seed,
            )
            for path in paths
        ]
    identifiers = [dataset.skill_id for dataset in datasets]
    if not datasets:
        raise ValueError("At least one self-generated dataset is required")
    if len(identifiers) != len(set(identifiers)):
        raise ValueError("Loaded self-generated skill identifiers must be unique")
    return tuple(datasets)


def train_recurrent_student(
    model: Any,
    paths: Mapping[str, Path] | Sequence[Path],
    *,
    updates: int,
    config: SequenceTrainingConfig | None = None,
    seed: int = 0,
    optimizer: Any | None = None,
) -> tuple[SequenceAwareStudentTrainer, StudentTrainingReport]:
    """Convenience entry point for applying V8 Student updates to RecurrentPPO."""

    resolved_config = config or SequenceTrainingConfig()
    datasets = load_self_generated_datasets(
        paths,
        max_examples_per_skill=resolved_config.max_examples_per_dataset,
        sample_seed=seed,
    )
    replay = BalancedSkillReplay(datasets, resolved_config, seed=seed)
    trainer = SequenceAwareStudentTrainer(model, resolved_config, optimizer=optimizer)
    return trainer, trainer.train(replay, updates=updates)
